using Microsoft.Data.SqlClient.Server;

namespace BCryptSS
{
    public class BCryptFunctions
    {
        /// <summary>
        /// Verifies that the BCrypt hash of the given text (password) matches the provided hash.
        /// </summary>
        /// <param name="password">The password to verify.</param>
        /// <param name="hash">The previously-generated password hash.</param>
        /// <returns>True if the hashes match, otherwise false.</returns>
        [SqlFunction]
        public static bool CheckPassword(string password, string hash)
        {
            return BCrypt.Net.BCrypt.Verify(password, hash);
        }

        /// <summary>
        /// Generates a BCrypt hash of a given password using a salt generated by BCrypt.Net.BCrypt.GenerateSalt.
        /// </summary>
        /// <param name="password">The password to hash.</param>
        [SqlFunction]
        public static string HashPassword(string password)
        {
            return BCrypt.Net.BCrypt.HashPassword(password.ToString(), BCrypt.Net.BCrypt.GenerateSalt());
        }
    }
}
